services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      USERNAME: bill
      PASSWORD: gates
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 2022:22/tcp
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
    volumes:
        -  /home/jdh8d/tmp/dockur/win-storage:/storage
        -  /home/jdh8d/tmp/dockur/oem:/oem

